spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456


logging:
  level:
    root: warn
    cn.myfreecloud.mapper: trace
  pattern:
    # 日志级别,日志内容,换行
    console: '%p %d{YYYY-MM-dd HH:mm:ss,SSS} %m %n'
#    console: '%-5p %d{MM-dd HH:mm:ss,SSS} %m  (%F:%L) \n'


mybatis-plus:
  mapper-locations: classpath*:cn/myfreecloud/mapper/*.xml