spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123


logging:
  level:
    root: warn
    cn.myfreecloud.mapper: trace
  pattern:
    console: '%p%m%n'
